title:        RRT
tagline:      'Reproducibile R Toolkit'
description:  'Reproducibile R Toolkit'
permalink:    /:year/:month/:title/
base:         http://revolutionanalytics.github.io/RRT/
url:          http://revolutionanalytics.github.io/RRT/
author:
  name:       'Scott Chamberlain'
  email:      'myrmecocystus@gmail.com'
markdown:     rdiscount
highlighter:      pygments
paginate:     3
version:      0.1
exclude:      ['*.Rmd']
